apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-principal-namespace-reader
  namespace: <Your-Namespace>
subjects:
- kind: User
  name: "servicePrincipal:<Service-Principal-App-ID>"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io
