canary:
  enabled: true

  # Service configuration with multiple ports
  service:
    annotations:
      "prometheus.io/scrape": "true"
      "prometheus.io/path": "/metrics"
      "prometheus.io/port": "24663"
    ports:
      - name: http-management
        port: 24661
        targetPort: 24661
        protocol: TCP
      - name: http-service
        port: 24663
        targetPort: 24663
        protocol: TCP
      - name: http-status
        port: 24664
        targetPort: 24664
        protocol: TCP
    trafficPolicy:  # Mutual TLS and traffic control
      tls:
        mode: ISTIO_MUTUAL  # Enable mutual TLS for the service

  # Canary analysis and traffic routing configuration
  analysis:
    interval: 1m               # How often Flagger checks metrics during canary rollout
    threshold: 5                # Number of analysis checks before rollback
    maxWeight: 50               # Maximum percentage of traffic sent to canary
    stepWeight: 10              # Step percentage increase for traffic to canary
    metrics:
      - name: "request-success-rate"
        threshold: 99           # Rollback if request success rate is below this
        interval: 1m
      - name: "request-duration"
        threshold: 500          # Rollback if request duration exceeds this (in ms)
        interval: 30s

  # Istio Gateway and TrafficRouting configuration
  trafficRouting:
    istio:
      gateways:
        - istio-system/my-gateway   # Define the Istio gateway used for ingress
      hosts:
        - "*.example.com"           # Hosts for routing
      http:
        - match:
            - uri:
                prefix: "/management"  # Route traffic with the prefix /management
          rewrite:
            uri: "/new-management"     # Optional URI rewrite
          route:
            - destination:
                host: {{ .Release.Name }}-primary  # Primary service
                port:
                  number: 24661
              weight: 90   # 90% of traffic to primary
            - destination:
                host: {{ .Release.Name }}-canary   # Canary service
                port:
                  number: 24661
              weight: 10   # 10% of traffic to canary
        - match:
            - uri:
                prefix: "/service"      # Route traffic with the prefix /service
          rewrite:
            uri: "/new-service"         # Optional URI rewrite
          route:
            - destination:
                host: {{ .Release.Name }}-primary
                port:
                  number: 24663
              weight: 90
            - destination:
                host: {{ .Release.Name }}-canary
                port:
                  number: 24663
              weight: 10
        - match:
            - uri:
                prefix: "/status"       # Route traffic with the prefix /status
          route:
            - destination:
                host: {{ .Release.Name }}-primary
                port:
                  number: 24664
              weight: 90
            - destination:
                host: {{ .Release.Name }}-canary
                port:
                  number: 24664
              weight: 10

  # Webhook for load testing with `hey` command
  loadtest:
    url: "http://flagger-loadtester.test/load-test"  # Load test service URL
    cmd: "hey -z 1m -q 10 http://{{ .Release.Name }}-canary.{{ .Release.Namespace }}:24663/your-endpoint"
